package com.boot.dao.master;

import com.boot.model.master.BokaMembers;
import com.boot.model.master.BokaMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BokaMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int countByExample(BokaMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int deleteByExample(BokaMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int insert(BokaMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int insertSelective(BokaMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    List<BokaMembers> selectByExample(BokaMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    BokaMembers selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") BokaMembers record, @Param("example") BokaMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int updateByExample(@Param("record") BokaMembers record, @Param("example") BokaMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int updateByPrimaryKeySelective(BokaMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_members
     *
     * @mbggenerated Mon Jul 03 17:57:41 CST 2017
     */
    int updateByPrimaryKey(BokaMembers record);
}