package com.boot.dao.master;

import com.boot.model.master.BokaEduresource;
import com.boot.model.master.BokaEduresourceExample;
import com.boot.model.master.BokaEduresourceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BokaEduresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int countByExample(BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int deleteByExample(BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int insert(BokaEduresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int insertSelective(BokaEduresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    List<BokaEduresourceWithBLOBs> selectByExampleWithBLOBs(BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    List<BokaEduresource> selectByExample(BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    BokaEduresourceWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") BokaEduresourceWithBLOBs record, @Param("example") BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BokaEduresourceWithBLOBs record, @Param("example") BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByExample(@Param("record") BokaEduresource record, @Param("example") BokaEduresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByPrimaryKeySelective(BokaEduresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BokaEduresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    int updateByPrimaryKey(BokaEduresource record);
}