package com.boot.dao.master;

import com.boot.model.master.BokaNews;
import com.boot.model.master.BokaNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BokaNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int countByExample(BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int deleteByExample(BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int insert(BokaNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int insertSelective(BokaNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    List<BokaNews> selectByExampleWithBLOBs(BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    List<BokaNews> selectByExample(BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    BokaNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") BokaNews record, @Param("example") BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BokaNews record, @Param("example") BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByExample(@Param("record") BokaNews record, @Param("example") BokaNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByPrimaryKeySelective(BokaNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BokaNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_news
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    int updateByPrimaryKey(BokaNews record);
}