package com.boot.dao.master;

import com.boot.model.master.BokaNewscontent;
import com.boot.model.master.BokaNewscontentExample;
import com.boot.model.master.BokaNewscontentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BokaNewscontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int countByExample(BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int deleteByExample(BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int insert(BokaNewscontentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int insertSelective(BokaNewscontentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    List<BokaNewscontentWithBLOBs> selectByExampleWithBLOBs(BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    List<BokaNewscontent> selectByExample(BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    BokaNewscontentWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") BokaNewscontentWithBLOBs record, @Param("example") BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BokaNewscontentWithBLOBs record, @Param("example") BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByExample(@Param("record") BokaNewscontent record, @Param("example") BokaNewscontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByPrimaryKeySelective(BokaNewscontentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BokaNewscontentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newscontent
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    int updateByPrimaryKey(BokaNewscontent record);
}