package com.boot.dao.master;

import com.boot.model.master.BokaResourcetypeclass;
import com.boot.model.master.BokaResourcetypeclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BokaResourcetypeclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int countByExample(BokaResourcetypeclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int deleteByExample(BokaResourcetypeclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int insert(BokaResourcetypeclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int insertSelective(BokaResourcetypeclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    List<BokaResourcetypeclass> selectByExample(BokaResourcetypeclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    BokaResourcetypeclass selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") BokaResourcetypeclass record, @Param("example") BokaResourcetypeclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int updateByExample(@Param("record") BokaResourcetypeclass record, @Param("example") BokaResourcetypeclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int updateByPrimaryKeySelective(BokaResourcetypeclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_resourcetypeclass
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    int updateByPrimaryKey(BokaResourcetypeclass record);
}