package com.boot.dao.cluster;

import com.boot.model.cluster.JsCategoriesDict;
import com.boot.model.cluster.JsCategoriesDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsCategoriesDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int countByExample(JsCategoriesDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int deleteByExample(JsCategoriesDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int insert(JsCategoriesDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int insertSelective(JsCategoriesDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    List<JsCategoriesDict> selectByExample(JsCategoriesDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    JsCategoriesDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsCategoriesDict record, @Param("example") JsCategoriesDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int updateByExample(@Param("record") JsCategoriesDict record, @Param("example") JsCategoriesDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int updateByPrimaryKeySelective(JsCategoriesDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_categories_dict
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    int updateByPrimaryKey(JsCategoriesDict record);
}