package com.boot.dao.cluster;

import com.boot.model.cluster.JsEbookTemplate;
import com.boot.model.cluster.JsEbookTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsEbookTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int countByExample(JsEbookTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int deleteByExample(JsEbookTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int insert(JsEbookTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int insertSelective(JsEbookTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    List<JsEbookTemplate> selectByExample(JsEbookTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    JsEbookTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsEbookTemplate record, @Param("example") JsEbookTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int updateByExample(@Param("record") JsEbookTemplate record, @Param("example") JsEbookTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int updateByPrimaryKeySelective(JsEbookTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_ebook_template
     *
     * @mbggenerated Tue Aug 01 14:16:04 CST 2017
     */
    int updateByPrimaryKey(JsEbookTemplate record);
}