package com.boot.dao.cluster;

import com.boot.model.cluster.JsResource;
import com.boot.model.cluster.JsResourceExample;
import com.boot.model.cluster.JsResourceWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int countByExample(JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int deleteByExample(JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int insert(JsResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int insertSelective(JsResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    List<JsResourceWithBLOBs> selectByExampleWithBLOBs(JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    List<JsResource> selectByExample(JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    JsResourceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsResourceWithBLOBs record, @Param("example") JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") JsResourceWithBLOBs record, @Param("example") JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByExample(@Param("record") JsResource record, @Param("example") JsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByPrimaryKeySelective(JsResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(JsResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    int updateByPrimaryKey(JsResource record);
}