package com.boot.dao.cluster;

import com.boot.model.cluster.JsResourceCopy;
import com.boot.model.cluster.JsResourceCopyExample;
import com.boot.model.cluster.JsResourceCopyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsResourceCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int countByExample(JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int deleteByExample(JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int insert(JsResourceCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int insertSelective(JsResourceCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    List<JsResourceCopyWithBLOBs> selectByExampleWithBLOBs(JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    List<JsResourceCopy> selectByExample(JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    JsResourceCopyWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsResourceCopyWithBLOBs record, @Param("example") JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") JsResourceCopyWithBLOBs record, @Param("example") JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByExample(@Param("record") JsResourceCopy record, @Param("example") JsResourceCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(JsResourceCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(JsResourceCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_copy
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    int updateByPrimaryKey(JsResourceCopy record);
}