package com.boot.dao.cluster;

import com.boot.model.cluster.JsResourceStatistics;
import com.boot.model.cluster.JsResourceStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsResourceStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int countByExample(JsResourceStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int deleteByExample(JsResourceStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int insert(JsResourceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int insertSelective(JsResourceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    List<JsResourceStatistics> selectByExample(JsResourceStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    JsResourceStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsResourceStatistics record, @Param("example") JsResourceStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int updateByExample(@Param("record") JsResourceStatistics record, @Param("example") JsResourceStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int updateByPrimaryKeySelective(JsResourceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_resource_statistics
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    int updateByPrimaryKey(JsResourceStatistics record);
}