package com.boot.dao.cluster;

import com.boot.model.cluster.Temp;
import com.boot.model.cluster.TempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int countByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int deleteByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int insert(Temp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int insertSelective(Temp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    List<Temp> selectByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") Temp record, @Param("example") TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    int updateByExample(@Param("record") Temp record, @Param("example") TempExample example);
}