package com.boot.model.master;

public class BokaNewscontentWithBLOBs extends BokaNewscontent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.content
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.summary
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.extension
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String extension;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.content
     *
     * @return the value of boka_newscontent.content
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.content
     *
     * @param content the value for boka_newscontent.content
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.summary
     *
     * @return the value of boka_newscontent.summary
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.summary
     *
     * @param summary the value for boka_newscontent.summary
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.extension
     *
     * @return the value of boka_newscontent.extension
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.extension
     *
     * @param extension the value for boka_newscontent.extension
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }
}