package com.boot.model.master;

public class BokaNewscontent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.id
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.classid
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private Short classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.seotitle
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String seotitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.seodescription
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String seodescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_newscontent.seokeywords
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    private String seokeywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.id
     *
     * @return the value of boka_newscontent.id
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.id
     *
     * @param id the value for boka_newscontent.id
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.classid
     *
     * @return the value of boka_newscontent.classid
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public Short getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.classid
     *
     * @param classid the value for boka_newscontent.classid
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setClassid(Short classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.seotitle
     *
     * @return the value of boka_newscontent.seotitle
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getSeotitle() {
        return seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.seotitle
     *
     * @param seotitle the value for boka_newscontent.seotitle
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setSeotitle(String seotitle) {
        this.seotitle = seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.seodescription
     *
     * @return the value of boka_newscontent.seodescription
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getSeodescription() {
        return seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.seodescription
     *
     * @param seodescription the value for boka_newscontent.seodescription
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setSeodescription(String seodescription) {
        this.seodescription = seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_newscontent.seokeywords
     *
     * @return the value of boka_newscontent.seokeywords
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public String getSeokeywords() {
        return seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_newscontent.seokeywords
     *
     * @param seokeywords the value for boka_newscontent.seokeywords
     *
     * @mbggenerated Mon Jul 17 10:34:31 CST 2017
     */
    public void setSeokeywords(String seokeywords) {
        this.seokeywords = seokeywords;
    }
}