package com.boot.model.master;

public class BokaEduresourceWithBLOBs extends BokaEduresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.photo
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.content
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.extension
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.eduresource18
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String eduresource18;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.photo
     *
     * @return the value of boka_eduresource.photo
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.photo
     *
     * @param photo the value for boka_eduresource.photo
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.content
     *
     * @return the value of boka_eduresource.content
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.content
     *
     * @param content the value for boka_eduresource.content
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.extension
     *
     * @return the value of boka_eduresource.extension
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.extension
     *
     * @param extension the value for boka_eduresource.extension
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.eduresource18
     *
     * @return the value of boka_eduresource.eduresource18
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getEduresource18() {
        return eduresource18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.eduresource18
     *
     * @param eduresource18 the value for boka_eduresource.eduresource18
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setEduresource18(String eduresource18) {
        this.eduresource18 = eduresource18;
    }
}