package com.boot.model.master;

import java.util.ArrayList;
import java.util.List;

public class BokaEduresourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public BokaEduresourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull(){
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOldidIsNull() {
            addCriterion("oldid is null");
            return (Criteria) this;
        }

        public Criteria andOldidIsNotNull() {
            addCriterion("oldid is not null");
            return (Criteria) this;
        }

        public Criteria andOldidEqualTo(Integer value) {
            addCriterion("oldid =", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidNotEqualTo(Integer value) {
            addCriterion("oldid <>", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidGreaterThan(Integer value) {
            addCriterion("oldid >", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidGreaterThanOrEqualTo(Integer value) {
            addCriterion("oldid >=", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidLessThan(Integer value) {
            addCriterion("oldid <", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidLessThanOrEqualTo(Integer value) {
            addCriterion("oldid <=", value, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidIn(List<Integer> values) {
            addCriterion("oldid in", values, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidNotIn(List<Integer> values) {
            addCriterion("oldid not in", values, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidBetween(Integer value1, Integer value2) {
            addCriterion("oldid between", value1, value2, "oldid");
            return (Criteria) this;
        }

        public Criteria andOldidNotBetween(Integer value1, Integer value2) {
            addCriterion("oldid not between", value1, value2, "oldid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andClassidIsNull() {
            addCriterion("classid is null");
            return (Criteria) this;
        }

        public Criteria andClassidIsNotNull() {
            addCriterion("classid is not null");
            return (Criteria) this;
        }

        public Criteria andClassidEqualTo(String value) {
            addCriterion("classid =", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotEqualTo(String value) {
            addCriterion("classid <>", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidGreaterThan(String value) {
            addCriterion("classid >", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidGreaterThanOrEqualTo(String value) {
            addCriterion("classid >=", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLessThan(String value) {
            addCriterion("classid <", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLessThanOrEqualTo(String value) {
            addCriterion("classid <=", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLike(String value) {
            addCriterion("classid like", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotLike(String value) {
            addCriterion("classid not like", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidIn(List<String> values) {
            addCriterion("classid in", values, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotIn(List<String> values) {
            addCriterion("classid not in", values, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidBetween(String value1, String value2) {
            addCriterion("classid between", value1, value2, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotBetween(String value1, String value2) {
            addCriterion("classid not between", value1, value2, "classid");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNull() {
            addCriterion("filesize is null");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNotNull() {
            addCriterion("filesize is not null");
            return (Criteria) this;
        }

        public Criteria andFilesizeEqualTo(String value) {
            addCriterion("filesize =", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotEqualTo(String value) {
            addCriterion("filesize <>", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThan(String value) {
            addCriterion("filesize >", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThanOrEqualTo(String value) {
            addCriterion("filesize >=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThan(String value) {
            addCriterion("filesize <", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThanOrEqualTo(String value) {
            addCriterion("filesize <=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLike(String value) {
            addCriterion("filesize like", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotLike(String value) {
            addCriterion("filesize not like", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeIn(List<String> values) {
            addCriterion("filesize in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotIn(List<String> values) {
            addCriterion("filesize not in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeBetween(String value1, String value2) {
            addCriterion("filesize between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotBetween(String value1, String value2) {
            addCriterion("filesize not between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andGradeclassIsNull() {
            addCriterion("gradeclass is null");
            return (Criteria) this;
        }

        public Criteria andGradeclassIsNotNull() {
            addCriterion("gradeclass is not null");
            return (Criteria) this;
        }

        public Criteria andGradeclassEqualTo(String value) {
            addCriterion("gradeclass =", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassNotEqualTo(String value) {
            addCriterion("gradeclass <>", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassGreaterThan(String value) {
            addCriterion("gradeclass >", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassGreaterThanOrEqualTo(String value) {
            addCriterion("gradeclass >=", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassLessThan(String value) {
            addCriterion("gradeclass <", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassLessThanOrEqualTo(String value) {
            addCriterion("gradeclass <=", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassLike(String value) {
            addCriterion("gradeclass like", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassNotLike(String value) {
            addCriterion("gradeclass not like", value, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassIn(List<String> values) {
            addCriterion("gradeclass in", values, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassNotIn(List<String> values) {
            addCriterion("gradeclass not in", values, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassBetween(String value1, String value2) {
            addCriterion("gradeclass between", value1, value2, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andGradeclassNotBetween(String value1, String value2) {
            addCriterion("gradeclass not between", value1, value2, "gradeclass");
            return (Criteria) this;
        }

        public Criteria andResourcetypeIsNull() {
            addCriterion("resourcetype is null");
            return (Criteria) this;
        }

        public Criteria andResourcetypeIsNotNull() {
            addCriterion("resourcetype is not null");
            return (Criteria) this;
        }

        public Criteria andResourcetypeEqualTo(Byte value) {
            addCriterion("resourcetype =", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeNotEqualTo(Byte value) {
            addCriterion("resourcetype <>", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeGreaterThan(Byte value) {
            addCriterion("resourcetype >", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("resourcetype >=", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeLessThan(Byte value) {
            addCriterion("resourcetype <", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeLessThanOrEqualTo(Byte value) {
            addCriterion("resourcetype <=", value, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeIn(List<Byte> values) {
            addCriterion("resourcetype in", values, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeNotIn(List<Byte> values) {
            addCriterion("resourcetype not in", values, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeBetween(Byte value1, Byte value2) {
            addCriterion("resourcetype between", value1, value2, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andResourcetypeNotBetween(Byte value1, Byte value2) {
            addCriterion("resourcetype not between", value1, value2, "resourcetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeIsNull() {
            addCriterion("filetype is null");
            return (Criteria) this;
        }

        public Criteria andFiletypeIsNotNull() {
            addCriterion("filetype is not null");
            return (Criteria) this;
        }

        public Criteria andFiletypeEqualTo(String value) {
            addCriterion("filetype =", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotEqualTo(String value) {
            addCriterion("filetype <>", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeGreaterThan(String value) {
            addCriterion("filetype >", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeGreaterThanOrEqualTo(String value) {
            addCriterion("filetype >=", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeLessThan(String value) {
            addCriterion("filetype <", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeLessThanOrEqualTo(String value) {
            addCriterion("filetype <=", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeLike(String value) {
            addCriterion("filetype like", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotLike(String value) {
            addCriterion("filetype not like", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeIn(List<String> values) {
            addCriterion("filetype in", values, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotIn(List<String> values) {
            addCriterion("filetype not in", values, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeBetween(String value1, String value2) {
            addCriterion("filetype between", value1, value2, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotBetween(String value1, String value2) {
            addCriterion("filetype not between", value1, value2, "filetype");
            return (Criteria) this;
        }

        public Criteria andDownurlIsNull() {
            addCriterion("downurl is null");
            return (Criteria) this;
        }

        public Criteria andDownurlIsNotNull() {
            addCriterion("downurl is not null");
            return (Criteria) this;
        }

        public Criteria andDownurlEqualTo(String value) {
            addCriterion("downurl =", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlNotEqualTo(String value) {
            addCriterion("downurl <>", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlGreaterThan(String value) {
            addCriterion("downurl >", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlGreaterThanOrEqualTo(String value) {
            addCriterion("downurl >=", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlLessThan(String value) {
            addCriterion("downurl <", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlLessThanOrEqualTo(String value) {
            addCriterion("downurl <=", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlLike(String value) {
            addCriterion("downurl like", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlNotLike(String value) {
            addCriterion("downurl not like", value, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlIn(List<String> values) {
            addCriterion("downurl in", values, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlNotIn(List<String> values) {
            addCriterion("downurl not in", values, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlBetween(String value1, String value2) {
            addCriterion("downurl between", value1, value2, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownurlNotBetween(String value1, String value2) {
            addCriterion("downurl not between", value1, value2, "downurl");
            return (Criteria) this;
        }

        public Criteria andDownclickIsNull() {
            addCriterion("downclick is null");
            return (Criteria) this;
        }

        public Criteria andDownclickIsNotNull() {
            addCriterion("downclick is not null");
            return (Criteria) this;
        }

        public Criteria andDownclickEqualTo(String value) {
            addCriterion("downclick =", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickNotEqualTo(String value) {
            addCriterion("downclick <>", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickGreaterThan(String value) {
            addCriterion("downclick >", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickGreaterThanOrEqualTo(String value) {
            addCriterion("downclick >=", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickLessThan(String value) {
            addCriterion("downclick <", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickLessThanOrEqualTo(String value) {
            addCriterion("downclick <=", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickLike(String value) {
            addCriterion("downclick like", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickNotLike(String value) {
            addCriterion("downclick not like", value, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickIn(List<String> values) {
            addCriterion("downclick in", values, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickNotIn(List<String> values) {
            addCriterion("downclick not in", values, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickBetween(String value1, String value2) {
            addCriterion("downclick between", value1, value2, "downclick");
            return (Criteria) this;
        }

        public Criteria andDownclickNotBetween(String value1, String value2) {
            addCriterion("downclick not between", value1, value2, "downclick");
            return (Criteria) this;
        }

        public Criteria andOtherurlIsNull() {
            addCriterion("otherurl is null");
            return (Criteria) this;
        }

        public Criteria andOtherurlIsNotNull() {
            addCriterion("otherurl is not null");
            return (Criteria) this;
        }

        public Criteria andOtherurlEqualTo(String value) {
            addCriterion("otherurl =", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlNotEqualTo(String value) {
            addCriterion("otherurl <>", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlGreaterThan(String value) {
            addCriterion("otherurl >", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlGreaterThanOrEqualTo(String value) {
            addCriterion("otherurl >=", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlLessThan(String value) {
            addCriterion("otherurl <", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlLessThanOrEqualTo(String value) {
            addCriterion("otherurl <=", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlLike(String value) {
            addCriterion("otherurl like", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlNotLike(String value) {
            addCriterion("otherurl not like", value, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlIn(List<String> values) {
            addCriterion("otherurl in", values, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlNotIn(List<String> values) {
            addCriterion("otherurl not in", values, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlBetween(String value1, String value2) {
            addCriterion("otherurl between", value1, value2, "otherurl");
            return (Criteria) this;
        }

        public Criteria andOtherurlNotBetween(String value1, String value2) {
            addCriterion("otherurl not between", value1, value2, "otherurl");
            return (Criteria) this;
        }

        public Criteria andModerateIsNull() {
            addCriterion("moderate is null");
            return (Criteria) this;
        }

        public Criteria andModerateIsNotNull() {
            addCriterion("moderate is not null");
            return (Criteria) this;
        }

        public Criteria andModerateEqualTo(Integer value) {
            addCriterion("moderate =", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateNotEqualTo(Byte value) {
            addCriterion("moderate <>", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateGreaterThan(Byte value) {
            addCriterion("moderate >", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateGreaterThanOrEqualTo(Byte value) {
            addCriterion("moderate >=", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateLessThan(Byte value) {
            addCriterion("moderate <", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateLessThanOrEqualTo(Byte value) {
            addCriterion("moderate <=", value, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateIn(List<Byte> values) {
            addCriterion("moderate in", values, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateNotIn(List<Byte> values) {
            addCriterion("moderate not in", values, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateBetween(Byte value1, Byte value2) {
            addCriterion("moderate between", value1, value2, "moderate");
            return (Criteria) this;
        }

        public Criteria andModerateNotBetween(Byte value1, Byte value2) {
            addCriterion("moderate not between", value1, value2, "moderate");
            return (Criteria) this;
        }

        public Criteria andKidIsNull() {
            addCriterion("kid is null");
            return (Criteria) this;
        }

        public Criteria andKidIsNotNull() {
            addCriterion("kid is not null");
            return (Criteria) this;
        }

        public Criteria andKidEqualTo(String value) {
            addCriterion("kid =", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotEqualTo(String value) {
            addCriterion("kid <>", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidGreaterThan(String value) {
            addCriterion("kid >", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidGreaterThanOrEqualTo(String value) {
            addCriterion("kid >=", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLessThan(String value) {
            addCriterion("kid <", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLessThanOrEqualTo(String value) {
            addCriterion("kid <=", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLike(String value) {
            addCriterion("kid like", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotLike(String value) {
            addCriterion("kid not like", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidIn(List<String> values) {
            addCriterion("kid in", values, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotIn(List<String> values) {
            addCriterion("kid not in", values, "kid");
            return (Criteria) this;
        }

        public Criteria andKidBetween(String value1, String value2) {
            addCriterion("kid between", value1, value2, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotBetween(String value1, String value2) {
            addCriterion("kid not between", value1, value2, "kid");
            return (Criteria) this;
        }

        public Criteria andCommendIsNull() {
            addCriterion("commend is null");
            return (Criteria) this;
        }

        public Criteria andCommendIsNotNull() {
            addCriterion("commend is not null");
            return (Criteria) this;
        }

        public Criteria andCommendEqualTo(Byte value) {
            addCriterion("commend =", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendNotEqualTo(Byte value) {
            addCriterion("commend <>", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendGreaterThan(Byte value) {
            addCriterion("commend >", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendGreaterThanOrEqualTo(Byte value) {
            addCriterion("commend >=", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendLessThan(Byte value) {
            addCriterion("commend <", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendLessThanOrEqualTo(Byte value) {
            addCriterion("commend <=", value, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendIn(List<Byte> values) {
            addCriterion("commend in", values, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendNotIn(List<Byte> values) {
            addCriterion("commend not in", values, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendBetween(Byte value1, Byte value2) {
            addCriterion("commend between", value1, value2, "commend");
            return (Criteria) this;
        }

        public Criteria andCommendNotBetween(Byte value1, Byte value2) {
            addCriterion("commend not between", value1, value2, "commend");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNull() {
            addCriterion("uploader is null");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNotNull() {
            addCriterion("uploader is not null");
            return (Criteria) this;
        }

        public Criteria andUploaderEqualTo(Integer value) {
            addCriterion("uploader =", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotEqualTo(Integer value) {
            addCriterion("uploader <>", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThan(Integer value) {
            addCriterion("uploader >", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThanOrEqualTo(Integer value) {
            addCriterion("uploader >=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThan(Integer value) {
            addCriterion("uploader <", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThanOrEqualTo(Integer value) {
            addCriterion("uploader <=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderIn(List<Integer> values) {
            addCriterion("uploader in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotIn(List<Integer> values) {
            addCriterion("uploader not in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderBetween(Integer value1, Integer value2) {
            addCriterion("uploader between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotBetween(Integer value1, Integer value2) {
            addCriterion("uploader not between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andViewsIsNull() {
            addCriterion("views is null");
            return (Criteria) this;
        }

        public Criteria andViewsIsNotNull() {
            addCriterion("views is not null");
            return (Criteria) this;
        }

        public Criteria andViewsEqualTo(Integer value) {
            addCriterion("views =", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotEqualTo(Integer value) {
            addCriterion("views <>", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThan(Integer value) {
            addCriterion("views >", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThanOrEqualTo(Integer value) {
            addCriterion("views >=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThan(Integer value) {
            addCriterion("views <", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThanOrEqualTo(Integer value) {
            addCriterion("views <=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsIn(List<Integer> values) {
            addCriterion("views in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotIn(List<Integer> values) {
            addCriterion("views not in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsBetween(Integer value1, Integer value2) {
            addCriterion("views between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotBetween(Integer value1, Integer value2) {
            addCriterion("views not between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andDatelineIsNull() {
            addCriterion("dateline is null");
            return (Criteria) this;
        }

        public Criteria andDatelineIsNotNull() {
            addCriterion("dateline is not null");
            return (Criteria) this;
        }

        public Criteria andDatelineEqualTo(Long value) {
            addCriterion("dateline =", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotEqualTo(Integer value) {
            addCriterion("dateline <>", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineGreaterThan(Integer value) {
            addCriterion("dateline >", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineGreaterThanOrEqualTo(Integer value) {
            addCriterion("dateline >=", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineLessThan(Integer value) {
            addCriterion("dateline <", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineLessThanOrEqualTo(Integer value) {
            addCriterion("dateline <=", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineIn(List<Integer> values) {
            addCriterion("dateline in", values, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotIn(List<Integer> values) {
            addCriterion("dateline not in", values, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineBetween(Integer value1, Integer value2) {
            addCriterion("dateline between", value1, value2, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotBetween(Integer value1, Integer value2) {
            addCriterion("dateline not between", value1, value2, "dateline");
            return (Criteria) this;
        }

        public Criteria andCreditIsNull() {
            addCriterion("credit is null");
            return (Criteria) this;
        }

        public Criteria andCreditIsNotNull() {
            addCriterion("credit is not null");
            return (Criteria) this;
        }

        public Criteria andCreditEqualTo(Integer value) {
            addCriterion("credit =", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotEqualTo(Integer value) {
            addCriterion("credit <>", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThan(Integer value) {
            addCriterion("credit >", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("credit >=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThan(Integer value) {
            addCriterion("credit <", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThanOrEqualTo(Integer value) {
            addCriterion("credit <=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditIn(List<Integer> values) {
            addCriterion("credit in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotIn(List<Integer> values) {
            addCriterion("credit not in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditBetween(Integer value1, Integer value2) {
            addCriterion("credit between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("credit not between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(Byte value) {
            addCriterion("rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(Byte value) {
            addCriterion("rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(Byte value) {
            addCriterion("rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(Byte value) {
            addCriterion("rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(Byte value) {
            addCriterion("rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(Byte value) {
            addCriterion("rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<Byte> values) {
            addCriterion("rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<Byte> values) {
            addCriterion("rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(Byte value1, Byte value2) {
            addCriterion("rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(Byte value1, Byte value2) {
            addCriterion("rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andTargetidIsNull() {
            addCriterion("targetid is null");
            return (Criteria) this;
        }

        public Criteria andTargetidIsNotNull() {
            addCriterion("targetid is not null");
            return (Criteria) this;
        }

        public Criteria andTargetidEqualTo(Integer value) {
            addCriterion("targetid =", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotEqualTo(Integer value) {
            addCriterion("targetid <>", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidGreaterThan(Integer value) {
            addCriterion("targetid >", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidGreaterThanOrEqualTo(Integer value) {
            addCriterion("targetid >=", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidLessThan(Integer value) {
            addCriterion("targetid <", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidLessThanOrEqualTo(Integer value) {
            addCriterion("targetid <=", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidIn(List<Integer> values) {
            addCriterion("targetid in", values, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotIn(List<Integer> values) {
            addCriterion("targetid not in", values, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidBetween(Integer value1, Integer value2) {
            addCriterion("targetid between", value1, value2, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotBetween(Integer value1, Integer value2) {
            addCriterion("targetid not between", value1, value2, "targetid");
            return (Criteria) this;
        }

        public Criteria andSeotitleIsNull() {
            addCriterion("seotitle is null");
            return (Criteria) this;
        }

        public Criteria andSeotitleIsNotNull() {
            addCriterion("seotitle is not null");
            return (Criteria) this;
        }

        public Criteria andSeotitleEqualTo(String value) {
            addCriterion("seotitle =", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotEqualTo(String value) {
            addCriterion("seotitle <>", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleGreaterThan(String value) {
            addCriterion("seotitle >", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleGreaterThanOrEqualTo(String value) {
            addCriterion("seotitle >=", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLessThan(String value) {
            addCriterion("seotitle <", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLessThanOrEqualTo(String value) {
            addCriterion("seotitle <=", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLike(String value) {
            addCriterion("seotitle like", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotLike(String value) {
            addCriterion("seotitle not like", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleIn(List<String> values) {
            addCriterion("seotitle in", values, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotIn(List<String> values) {
            addCriterion("seotitle not in", values, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleBetween(String value1, String value2) {
            addCriterion("seotitle between", value1, value2, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotBetween(String value1, String value2) {
            addCriterion("seotitle not between", value1, value2, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIsNull() {
            addCriterion("seodescription is null");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIsNotNull() {
            addCriterion("seodescription is not null");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionEqualTo(String value) {
            addCriterion("seodescription =", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotEqualTo(String value) {
            addCriterion("seodescription <>", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionGreaterThan(String value) {
            addCriterion("seodescription >", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("seodescription >=", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLessThan(String value) {
            addCriterion("seodescription <", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLessThanOrEqualTo(String value) {
            addCriterion("seodescription <=", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLike(String value) {
            addCriterion("seodescription like", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotLike(String value) {
            addCriterion("seodescription not like", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIn(List<String> values) {
            addCriterion("seodescription in", values, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotIn(List<String> values) {
            addCriterion("seodescription not in", values, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionBetween(String value1, String value2) {
            addCriterion("seodescription between", value1, value2, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotBetween(String value1, String value2) {
            addCriterion("seodescription not between", value1, value2, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIsNull() {
            addCriterion("seokeywords is null");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIsNotNull() {
            addCriterion("seokeywords is not null");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsEqualTo(String value) {
            addCriterion("seokeywords =", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotEqualTo(String value) {
            addCriterion("seokeywords <>", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsGreaterThan(String value) {
            addCriterion("seokeywords >", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("seokeywords >=", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLessThan(String value) {
            addCriterion("seokeywords <", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLessThanOrEqualTo(String value) {
            addCriterion("seokeywords <=", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLike(String value) {
            addCriterion("seokeywords like", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotLike(String value) {
            addCriterion("seokeywords not like", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIn(List<String> values) {
            addCriterion("seokeywords in", values, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotIn(List<String> values) {
            addCriterion("seokeywords not in", values, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsBetween(String value1, String value2) {
            addCriterion("seokeywords between", value1, value2, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotBetween(String value1, String value2) {
            addCriterion("seokeywords not between", value1, value2, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andLinkidIsNull() {
            addCriterion("linkid is null");
            return (Criteria) this;
        }

        public Criteria andLinkidIsNotNull() {
            addCriterion("linkid is not null");
            return (Criteria) this;
        }

        public Criteria andLinkidEqualTo(Short value) {
            addCriterion("linkid =", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotEqualTo(Short value) {
            addCriterion("linkid <>", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThan(Short value) {
            addCriterion("linkid >", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThanOrEqualTo(Short value) {
            addCriterion("linkid >=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThan(Short value) {
            addCriterion("linkid <", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThanOrEqualTo(Short value) {
            addCriterion("linkid <=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidIn(List<Short> values) {
            addCriterion("linkid in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotIn(List<Short> values) {
            addCriterion("linkid not in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidBetween(Short value1, Short value2) {
            addCriterion("linkid between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotBetween(Short value1, Short value2) {
            addCriterion("linkid not between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andMainbusidIsNull() {
            addCriterion("mainbusid is null");
            return (Criteria) this;
        }

        public Criteria andMainbusidIsNotNull() {
            addCriterion("mainbusid is not null");
            return (Criteria) this;
        }

        public Criteria andMainbusidEqualTo(Integer value) {
            addCriterion("mainbusid =", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidNotEqualTo(Integer value) {
            addCriterion("mainbusid <>", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidGreaterThan(Integer value) {
            addCriterion("mainbusid >", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mainbusid >=", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidLessThan(Integer value) {
            addCriterion("mainbusid <", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidLessThanOrEqualTo(Integer value) {
            addCriterion("mainbusid <=", value, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidIn(List<Integer> values) {
            addCriterion("mainbusid in", values, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidNotIn(List<Integer> values) {
            addCriterion("mainbusid not in", values, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidBetween(Integer value1, Integer value2) {
            addCriterion("mainbusid between", value1, value2, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andMainbusidNotBetween(Integer value1, Integer value2) {
            addCriterion("mainbusid not between", value1, value2, "mainbusid");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNull() {
            addCriterion("voteid is null");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNotNull() {
            addCriterion("voteid is not null");
            return (Criteria) this;
        }

        public Criteria andVoteidEqualTo(Short value) {
            addCriterion("voteid =", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotEqualTo(Short value) {
            addCriterion("voteid <>", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThan(Short value) {
            addCriterion("voteid >", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThanOrEqualTo(Short value) {
            addCriterion("voteid >=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThan(Short value) {
            addCriterion("voteid <", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThanOrEqualTo(Short value) {
            addCriterion("voteid <=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidIn(List<Short> values) {
            addCriterion("voteid in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotIn(List<Short> values) {
            addCriterion("voteid not in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidBetween(Short value1, Short value2) {
            addCriterion("voteid between", value1, value2, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotBetween(Short value1, Short value2) {
            addCriterion("voteid not between", value1, value2, "voteid");
            return (Criteria) this;
        }

        public Criteria andDigIsNull() {
            addCriterion("dig is null");
            return (Criteria) this;
        }

        public Criteria andDigIsNotNull() {
            addCriterion("dig is not null");
            return (Criteria) this;
        }

        public Criteria andDigEqualTo(Short value) {
            addCriterion("dig =", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigNotEqualTo(Short value) {
            addCriterion("dig <>", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigGreaterThan(Short value) {
            addCriterion("dig >", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigGreaterThanOrEqualTo(Short value) {
            addCriterion("dig >=", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigLessThan(Short value) {
            addCriterion("dig <", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigLessThanOrEqualTo(Short value) {
            addCriterion("dig <=", value, "dig");
            return (Criteria) this;
        }

        public Criteria andDigIn(List<Short> values) {
            addCriterion("dig in", values, "dig");
            return (Criteria) this;
        }

        public Criteria andDigNotIn(List<Short> values) {
            addCriterion("dig not in", values, "dig");
            return (Criteria) this;
        }

        public Criteria andDigBetween(Short value1, Short value2) {
            addCriterion("dig between", value1, value2, "dig");
            return (Criteria) this;
        }

        public Criteria andDigNotBetween(Short value1, Short value2) {
            addCriterion("dig not between", value1, value2, "dig");
            return (Criteria) this;
        }

        public Criteria andEduresource6IsNull() {
            addCriterion("eduresource6 is null");
            return (Criteria) this;
        }

        public Criteria andEduresource6IsNotNull() {
            addCriterion("eduresource6 is not null");
            return (Criteria) this;
        }

        public Criteria andEduresource6EqualTo(String value) {
            addCriterion("eduresource6 =", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6NotEqualTo(String value) {
            addCriterion("eduresource6 <>", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6GreaterThan(String value) {
            addCriterion("eduresource6 >", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6GreaterThanOrEqualTo(String value) {
            addCriterion("eduresource6 >=", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6LessThan(String value) {
            addCriterion("eduresource6 <", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6LessThanOrEqualTo(String value) {
            addCriterion("eduresource6 <=", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6Like(String value) {
            addCriterion("eduresource6 like", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6NotLike(String value) {
            addCriterion("eduresource6 not like", value, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6In(List<String> values) {
            addCriterion("eduresource6 in", values, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6NotIn(List<String> values) {
            addCriterion("eduresource6 not in", values, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6Between(String value1, String value2) {
            addCriterion("eduresource6 between", value1, value2, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andEduresource6NotBetween(String value1, String value2) {
            addCriterion("eduresource6 not between", value1, value2, "eduresource6");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andActivetimeIsNull() {
            addCriterion("activetime is null");
            return (Criteria) this;
        }

        public Criteria andActivetimeIsNotNull() {
            addCriterion("activetime is not null");
            return (Criteria) this;
        }

        public Criteria andActivetimeEqualTo(Integer value) {
            addCriterion("activetime =", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeNotEqualTo(Integer value) {
            addCriterion("activetime <>", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeGreaterThan(Integer value) {
            addCriterion("activetime >", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("activetime >=", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeLessThan(Integer value) {
            addCriterion("activetime <", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeLessThanOrEqualTo(Integer value) {
            addCriterion("activetime <=", value, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeIn(List<Integer> values) {
            addCriterion("activetime in", values, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeNotIn(List<Integer> values) {
            addCriterion("activetime not in", values, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeBetween(Integer value1, Integer value2) {
            addCriterion("activetime between", value1, value2, "activetime");
            return (Criteria) this;
        }

        public Criteria andActivetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("activetime not between", value1, value2, "activetime");
            return (Criteria) this;
        }

        public Criteria andEduresource11IsNull() {
            addCriterion("eduresource11 is null");
            return (Criteria) this;
        }

        public Criteria andEduresource11IsNotNull() {
            addCriterion("eduresource11 is not null");
            return (Criteria) this;
        }

        public Criteria andEduresource11EqualTo(String value) {
            addCriterion("eduresource11 =", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11NotEqualTo(String value) {
            addCriterion("eduresource11 <>", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11GreaterThan(String value) {
            addCriterion("eduresource11 >", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11GreaterThanOrEqualTo(String value) {
            addCriterion("eduresource11 >=", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11LessThan(String value) {
            addCriterion("eduresource11 <", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11LessThanOrEqualTo(String value) {
            addCriterion("eduresource11 <=", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11Like(String value) {
            addCriterion("eduresource11 like", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11NotLike(String value) {
            addCriterion("eduresource11 not like", value, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11In(List<String> values) {
            addCriterion("eduresource11 in", values, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11NotIn(List<String> values) {
            addCriterion("eduresource11 not in", values, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11Between(String value1, String value2) {
            addCriterion("eduresource11 between", value1, value2, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource11NotBetween(String value1, String value2) {
            addCriterion("eduresource11 not between", value1, value2, "eduresource11");
            return (Criteria) this;
        }

        public Criteria andEduresource13IsNull() {
            addCriterion("eduresource13 is null");
            return (Criteria) this;
        }

        public Criteria andEduresource13IsNotNull() {
            addCriterion("eduresource13 is not null");
            return (Criteria) this;
        }

        public Criteria andEduresource13EqualTo(String value) {
            addCriterion("eduresource13 =", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13NotEqualTo(String value) {
            addCriterion("eduresource13 <>", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13GreaterThan(String value) {
            addCriterion("eduresource13 >", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13GreaterThanOrEqualTo(String value) {
            addCriterion("eduresource13 >=", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13LessThan(String value) {
            addCriterion("eduresource13 <", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13LessThanOrEqualTo(String value) {
            addCriterion("eduresource13 <=", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13Like(String value) {
            addCriterion("eduresource13 like", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13NotLike(String value) {
            addCriterion("eduresource13 not like", value, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13In(List<String> values) {
            addCriterion("eduresource13 in", values, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13NotIn(List<String> values) {
            addCriterion("eduresource13 not in", values, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13Between(String value1, String value2) {
            addCriterion("eduresource13 between", value1, value2, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource13NotBetween(String value1, String value2) {
            addCriterion("eduresource13 not between", value1, value2, "eduresource13");
            return (Criteria) this;
        }

        public Criteria andEduresource20IsNull() {
            addCriterion("eduresource20 is null");
            return (Criteria) this;
        }

        public Criteria andEduresource20IsNotNull() {
            addCriterion("eduresource20 is not null");
            return (Criteria) this;
        }

        public Criteria andEduresource20EqualTo(String value) {
            addCriterion("eduresource20 =", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20NotEqualTo(String value) {
            addCriterion("eduresource20 <>", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20GreaterThan(String value) {
            addCriterion("eduresource20 >", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20GreaterThanOrEqualTo(String value) {
            addCriterion("eduresource20 >=", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20LessThan(String value) {
            addCriterion("eduresource20 <", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20LessThanOrEqualTo(String value) {
            addCriterion("eduresource20 <=", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20Like(String value) {
            addCriterion("eduresource20 like", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20NotLike(String value) {
            addCriterion("eduresource20 not like", value, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20In(List<String> values) {
            addCriterion("eduresource20 in", values, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20NotIn(List<String> values) {
            addCriterion("eduresource20 not in", values, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20Between(String value1, String value2) {
            addCriterion("eduresource20 between", value1, value2, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andEduresource20NotBetween(String value1, String value2) {
            addCriterion("eduresource20 not between", value1, value2, "eduresource20");
            return (Criteria) this;
        }

        public Criteria andDownloadsIsNull() {
            addCriterion("downloads is null");
            return (Criteria) this;
        }

        public Criteria andDownloadsIsNotNull() {
            addCriterion("downloads is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadsEqualTo(Integer value) {
            addCriterion("downloads =", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotEqualTo(Integer value) {
            addCriterion("downloads <>", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsGreaterThan(Integer value) {
            addCriterion("downloads >", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsGreaterThanOrEqualTo(Integer value) {
            addCriterion("downloads >=", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsLessThan(Integer value) {
            addCriterion("downloads <", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsLessThanOrEqualTo(Integer value) {
            addCriterion("downloads <=", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsIn(List<Integer> values) {
            addCriterion("downloads in", values, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotIn(List<Integer> values) {
            addCriterion("downloads not in", values, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsBetween(Integer value1, Integer value2) {
            addCriterion("downloads between", value1, value2, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotBetween(Integer value1, Integer value2) {
            addCriterion("downloads not between", value1, value2, "downloads");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_eduresource
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 07 17:12:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_eduresource
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}