package com.boot.model.master;

public class BokaResourcetypeclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.id
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.parentid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Short parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.sequence
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Short sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.name
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.ishidden
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Byte ishidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.extension
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.language
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.number
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.seotitle
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String seotitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.seodescription
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String seodescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.seokeywords
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String seokeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.uploader
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Short uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.orderid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.description
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.icon
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.recommend
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Byte recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.dateline
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Integer dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_resourcetypeclass.updatetime
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    private Integer updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.id
     *
     * @return the value of boka_resourcetypeclass.id
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.id
     *
     * @param id the value for boka_resourcetypeclass.id
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.parentid
     *
     * @return the value of boka_resourcetypeclass.parentid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Short getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.parentid
     *
     * @param parentid the value for boka_resourcetypeclass.parentid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setParentid(Short parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.sequence
     *
     * @return the value of boka_resourcetypeclass.sequence
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Short getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.sequence
     *
     * @param sequence the value for boka_resourcetypeclass.sequence
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setSequence(Short sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.name
     *
     * @return the value of boka_resourcetypeclass.name
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.name
     *
     * @param name the value for boka_resourcetypeclass.name
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.ishidden
     *
     * @return the value of boka_resourcetypeclass.ishidden
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Byte getIshidden() {
        return ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.ishidden
     *
     * @param ishidden the value for boka_resourcetypeclass.ishidden
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setIshidden(Byte ishidden) {
        this.ishidden = ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.extension
     *
     * @return the value of boka_resourcetypeclass.extension
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.extension
     *
     * @param extension the value for boka_resourcetypeclass.extension
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.language
     *
     * @return the value of boka_resourcetypeclass.language
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.language
     *
     * @param language the value for boka_resourcetypeclass.language
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.number
     *
     * @return the value of boka_resourcetypeclass.number
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.number
     *
     * @param number the value for boka_resourcetypeclass.number
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.seotitle
     *
     * @return the value of boka_resourcetypeclass.seotitle
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getSeotitle() {
        return seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.seotitle
     *
     * @param seotitle the value for boka_resourcetypeclass.seotitle
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setSeotitle(String seotitle) {
        this.seotitle = seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.seodescription
     *
     * @return the value of boka_resourcetypeclass.seodescription
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getSeodescription() {
        return seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.seodescription
     *
     * @param seodescription the value for boka_resourcetypeclass.seodescription
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setSeodescription(String seodescription) {
        this.seodescription = seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.seokeywords
     *
     * @return the value of boka_resourcetypeclass.seokeywords
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getSeokeywords() {
        return seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.seokeywords
     *
     * @param seokeywords the value for boka_resourcetypeclass.seokeywords
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setSeokeywords(String seokeywords) {
        this.seokeywords = seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.uploader
     *
     * @return the value of boka_resourcetypeclass.uploader
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Short getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.uploader
     *
     * @param uploader the value for boka_resourcetypeclass.uploader
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setUploader(Short uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.orderid
     *
     * @return the value of boka_resourcetypeclass.orderid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.orderid
     *
     * @param orderid the value for boka_resourcetypeclass.orderid
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.description
     *
     * @return the value of boka_resourcetypeclass.description
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.description
     *
     * @param description the value for boka_resourcetypeclass.description
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.icon
     *
     * @return the value of boka_resourcetypeclass.icon
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.icon
     *
     * @param icon the value for boka_resourcetypeclass.icon
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.recommend
     *
     * @return the value of boka_resourcetypeclass.recommend
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Byte getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.recommend
     *
     * @param recommend the value for boka_resourcetypeclass.recommend
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setRecommend(Byte recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.dateline
     *
     * @return the value of boka_resourcetypeclass.dateline
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Integer getDateline() {
        return dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.dateline
     *
     * @param dateline the value for boka_resourcetypeclass.dateline
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setDateline(Integer dateline) {
        this.dateline = dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_resourcetypeclass.updatetime
     *
     * @return the value of boka_resourcetypeclass.updatetime
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_resourcetypeclass.updatetime
     *
     * @param updatetime the value for boka_resourcetypeclass.updatetime
     *
     * @mbggenerated Sun Jul 09 11:06:17 CST 2017
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }
}