package com.boot.model.master;

import java.util.ArrayList;
import java.util.List;

public class BokaNewsclassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public BokaNewsclassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentid is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentid is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Short value) {
            addCriterion("parentid =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Short value) {
            addCriterion("parentid <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Short value) {
            addCriterion("parentid >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Short value) {
            addCriterion("parentid >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Short value) {
            addCriterion("parentid <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Short value) {
            addCriterion("parentid <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Short> values) {
            addCriterion("parentid in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Short> values) {
            addCriterion("parentid not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Short value1, Short value2) {
            addCriterion("parentid between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Short value1, Short value2) {
            addCriterion("parentid not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Short value) {
            addCriterion("sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Short value) {
            addCriterion("sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Short value) {
            addCriterion("sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Short value) {
            addCriterion("sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Short value) {
            addCriterion("sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Short value) {
            addCriterion("sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Short> values) {
            addCriterion("sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Short> values) {
            addCriterion("sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Short value1, Short value2) {
            addCriterion("sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Short value1, Short value2) {
            addCriterion("sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIshiddenIsNull() {
            addCriterion("ishidden is null");
            return (Criteria) this;
        }

        public Criteria andIshiddenIsNotNull() {
            addCriterion("ishidden is not null");
            return (Criteria) this;
        }

        public Criteria andIshiddenEqualTo(Byte value) {
            addCriterion("ishidden =", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenNotEqualTo(Byte value) {
            addCriterion("ishidden <>", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenGreaterThan(Byte value) {
            addCriterion("ishidden >", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenGreaterThanOrEqualTo(Byte value) {
            addCriterion("ishidden >=", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenLessThan(Byte value) {
            addCriterion("ishidden <", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenLessThanOrEqualTo(Byte value) {
            addCriterion("ishidden <=", value, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenIn(List<Byte> values) {
            addCriterion("ishidden in", values, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenNotIn(List<Byte> values) {
            addCriterion("ishidden not in", values, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenBetween(Byte value1, Byte value2) {
            addCriterion("ishidden between", value1, value2, "ishidden");
            return (Criteria) this;
        }

        public Criteria andIshiddenNotBetween(Byte value1, Byte value2) {
            addCriterion("ishidden not between", value1, value2, "ishidden");
            return (Criteria) this;
        }

        public Criteria andExtensionIsNull() {
            addCriterion("extension is null");
            return (Criteria) this;
        }

        public Criteria andExtensionIsNotNull() {
            addCriterion("extension is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionEqualTo(String value) {
            addCriterion("extension =", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotEqualTo(String value) {
            addCriterion("extension <>", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionGreaterThan(String value) {
            addCriterion("extension >", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionGreaterThanOrEqualTo(String value) {
            addCriterion("extension >=", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLessThan(String value) {
            addCriterion("extension <", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLessThanOrEqualTo(String value) {
            addCriterion("extension <=", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLike(String value) {
            addCriterion("extension like", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotLike(String value) {
            addCriterion("extension not like", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionIn(List<String> values) {
            addCriterion("extension in", values, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotIn(List<String> values) {
            addCriterion("extension not in", values, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionBetween(String value1, String value2) {
            addCriterion("extension between", value1, value2, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotBetween(String value1, String value2) {
            addCriterion("extension not between", value1, value2, "extension");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andSeotitleIsNull() {
            addCriterion("seotitle is null");
            return (Criteria) this;
        }

        public Criteria andSeotitleIsNotNull() {
            addCriterion("seotitle is not null");
            return (Criteria) this;
        }

        public Criteria andSeotitleEqualTo(String value) {
            addCriterion("seotitle =", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotEqualTo(String value) {
            addCriterion("seotitle <>", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleGreaterThan(String value) {
            addCriterion("seotitle >", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleGreaterThanOrEqualTo(String value) {
            addCriterion("seotitle >=", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLessThan(String value) {
            addCriterion("seotitle <", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLessThanOrEqualTo(String value) {
            addCriterion("seotitle <=", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleLike(String value) {
            addCriterion("seotitle like", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotLike(String value) {
            addCriterion("seotitle not like", value, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleIn(List<String> values) {
            addCriterion("seotitle in", values, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotIn(List<String> values) {
            addCriterion("seotitle not in", values, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleBetween(String value1, String value2) {
            addCriterion("seotitle between", value1, value2, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeotitleNotBetween(String value1, String value2) {
            addCriterion("seotitle not between", value1, value2, "seotitle");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIsNull() {
            addCriterion("seodescription is null");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIsNotNull() {
            addCriterion("seodescription is not null");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionEqualTo(String value) {
            addCriterion("seodescription =", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotEqualTo(String value) {
            addCriterion("seodescription <>", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionGreaterThan(String value) {
            addCriterion("seodescription >", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("seodescription >=", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLessThan(String value) {
            addCriterion("seodescription <", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLessThanOrEqualTo(String value) {
            addCriterion("seodescription <=", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionLike(String value) {
            addCriterion("seodescription like", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotLike(String value) {
            addCriterion("seodescription not like", value, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionIn(List<String> values) {
            addCriterion("seodescription in", values, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotIn(List<String> values) {
            addCriterion("seodescription not in", values, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionBetween(String value1, String value2) {
            addCriterion("seodescription between", value1, value2, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeodescriptionNotBetween(String value1, String value2) {
            addCriterion("seodescription not between", value1, value2, "seodescription");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIsNull() {
            addCriterion("seokeywords is null");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIsNotNull() {
            addCriterion("seokeywords is not null");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsEqualTo(String value) {
            addCriterion("seokeywords =", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotEqualTo(String value) {
            addCriterion("seokeywords <>", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsGreaterThan(String value) {
            addCriterion("seokeywords >", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("seokeywords >=", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLessThan(String value) {
            addCriterion("seokeywords <", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLessThanOrEqualTo(String value) {
            addCriterion("seokeywords <=", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsLike(String value) {
            addCriterion("seokeywords like", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotLike(String value) {
            addCriterion("seokeywords not like", value, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsIn(List<String> values) {
            addCriterion("seokeywords in", values, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotIn(List<String> values) {
            addCriterion("seokeywords not in", values, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsBetween(String value1, String value2) {
            addCriterion("seokeywords between", value1, value2, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andSeokeywordsNotBetween(String value1, String value2) {
            addCriterion("seokeywords not between", value1, value2, "seokeywords");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNull() {
            addCriterion("uploader is null");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNotNull() {
            addCriterion("uploader is not null");
            return (Criteria) this;
        }

        public Criteria andUploaderEqualTo(Short value) {
            addCriterion("uploader =", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotEqualTo(Short value) {
            addCriterion("uploader <>", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThan(Short value) {
            addCriterion("uploader >", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThanOrEqualTo(Short value) {
            addCriterion("uploader >=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThan(Short value) {
            addCriterion("uploader <", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThanOrEqualTo(Short value) {
            addCriterion("uploader <=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderIn(List<Short> values) {
            addCriterion("uploader in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotIn(List<Short> values) {
            addCriterion("uploader not in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderBetween(Short value1, Short value2) {
            addCriterion("uploader between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotBetween(Short value1, Short value2) {
            addCriterion("uploader not between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("icon is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("icon is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("icon =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("icon <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("icon >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("icon >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("icon <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("icon <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("icon like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("icon not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("icon in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("icon not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("icon between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("icon not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNull() {
            addCriterion("recommend is null");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNotNull() {
            addCriterion("recommend is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendEqualTo(Byte value) {
            addCriterion("recommend =", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotEqualTo(Byte value) {
            addCriterion("recommend <>", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThan(Byte value) {
            addCriterion("recommend >", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThanOrEqualTo(Byte value) {
            addCriterion("recommend >=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThan(Byte value) {
            addCriterion("recommend <", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThanOrEqualTo(Byte value) {
            addCriterion("recommend <=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendIn(List<Byte> values) {
            addCriterion("recommend in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotIn(List<Byte> values) {
            addCriterion("recommend not in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendBetween(Byte value1, Byte value2) {
            addCriterion("recommend between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotBetween(Byte value1, Byte value2) {
            addCriterion("recommend not between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andShowphotoIsNull() {
            addCriterion("showphoto is null");
            return (Criteria) this;
        }

        public Criteria andShowphotoIsNotNull() {
            addCriterion("showphoto is not null");
            return (Criteria) this;
        }

        public Criteria andShowphotoEqualTo(Short value) {
            addCriterion("showphoto =", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoNotEqualTo(Short value) {
            addCriterion("showphoto <>", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoGreaterThan(Short value) {
            addCriterion("showphoto >", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoGreaterThanOrEqualTo(Short value) {
            addCriterion("showphoto >=", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoLessThan(Short value) {
            addCriterion("showphoto <", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoLessThanOrEqualTo(Short value) {
            addCriterion("showphoto <=", value, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoIn(List<Short> values) {
            addCriterion("showphoto in", values, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoNotIn(List<Short> values) {
            addCriterion("showphoto not in", values, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoBetween(Short value1, Short value2) {
            addCriterion("showphoto between", value1, value2, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowphotoNotBetween(Short value1, Short value2) {
            addCriterion("showphoto not between", value1, value2, "showphoto");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsIsNull() {
            addCriterion("showcolumns is null");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsIsNotNull() {
            addCriterion("showcolumns is not null");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsEqualTo(Short value) {
            addCriterion("showcolumns =", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsNotEqualTo(Short value) {
            addCriterion("showcolumns <>", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsGreaterThan(Short value) {
            addCriterion("showcolumns >", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsGreaterThanOrEqualTo(Short value) {
            addCriterion("showcolumns >=", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsLessThan(Short value) {
            addCriterion("showcolumns <", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsLessThanOrEqualTo(Short value) {
            addCriterion("showcolumns <=", value, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsIn(List<Short> values) {
            addCriterion("showcolumns in", values, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsNotIn(List<Short> values) {
            addCriterion("showcolumns not in", values, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsBetween(Short value1, Short value2) {
            addCriterion("showcolumns between", value1, value2, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andShowcolumnsNotBetween(Short value1, Short value2) {
            addCriterion("showcolumns not between", value1, value2, "showcolumns");
            return (Criteria) this;
        }

        public Criteria andPhotowidthIsNull() {
            addCriterion("photowidth is null");
            return (Criteria) this;
        }

        public Criteria andPhotowidthIsNotNull() {
            addCriterion("photowidth is not null");
            return (Criteria) this;
        }

        public Criteria andPhotowidthEqualTo(Short value) {
            addCriterion("photowidth =", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthNotEqualTo(Short value) {
            addCriterion("photowidth <>", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthGreaterThan(Short value) {
            addCriterion("photowidth >", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthGreaterThanOrEqualTo(Short value) {
            addCriterion("photowidth >=", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthLessThan(Short value) {
            addCriterion("photowidth <", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthLessThanOrEqualTo(Short value) {
            addCriterion("photowidth <=", value, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthIn(List<Short> values) {
            addCriterion("photowidth in", values, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthNotIn(List<Short> values) {
            addCriterion("photowidth not in", values, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthBetween(Short value1, Short value2) {
            addCriterion("photowidth between", value1, value2, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotowidthNotBetween(Short value1, Short value2) {
            addCriterion("photowidth not between", value1, value2, "photowidth");
            return (Criteria) this;
        }

        public Criteria andPhotoheightIsNull() {
            addCriterion("photoheight is null");
            return (Criteria) this;
        }

        public Criteria andPhotoheightIsNotNull() {
            addCriterion("photoheight is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoheightEqualTo(Short value) {
            addCriterion("photoheight =", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightNotEqualTo(Short value) {
            addCriterion("photoheight <>", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightGreaterThan(Short value) {
            addCriterion("photoheight >", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightGreaterThanOrEqualTo(Short value) {
            addCriterion("photoheight >=", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightLessThan(Short value) {
            addCriterion("photoheight <", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightLessThanOrEqualTo(Short value) {
            addCriterion("photoheight <=", value, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightIn(List<Short> values) {
            addCriterion("photoheight in", values, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightNotIn(List<Short> values) {
            addCriterion("photoheight not in", values, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightBetween(Short value1, Short value2) {
            addCriterion("photoheight between", value1, value2, "photoheight");
            return (Criteria) this;
        }

        public Criteria andPhotoheightNotBetween(Short value1, Short value2) {
            addCriterion("photoheight not between", value1, value2, "photoheight");
            return (Criteria) this;
        }

        public Criteria andShowdigIsNull() {
            addCriterion("showdig is null");
            return (Criteria) this;
        }

        public Criteria andShowdigIsNotNull() {
            addCriterion("showdig is not null");
            return (Criteria) this;
        }

        public Criteria andShowdigEqualTo(Byte value) {
            addCriterion("showdig =", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigNotEqualTo(Byte value) {
            addCriterion("showdig <>", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigGreaterThan(Byte value) {
            addCriterion("showdig >", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigGreaterThanOrEqualTo(Byte value) {
            addCriterion("showdig >=", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigLessThan(Byte value) {
            addCriterion("showdig <", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigLessThanOrEqualTo(Byte value) {
            addCriterion("showdig <=", value, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigIn(List<Byte> values) {
            addCriterion("showdig in", values, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigNotIn(List<Byte> values) {
            addCriterion("showdig not in", values, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigBetween(Byte value1, Byte value2) {
            addCriterion("showdig between", value1, value2, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowdigNotBetween(Byte value1, Byte value2) {
            addCriterion("showdig not between", value1, value2, "showdig");
            return (Criteria) this;
        }

        public Criteria andShowsummaryIsNull() {
            addCriterion("showsummary is null");
            return (Criteria) this;
        }

        public Criteria andShowsummaryIsNotNull() {
            addCriterion("showsummary is not null");
            return (Criteria) this;
        }

        public Criteria andShowsummaryEqualTo(Byte value) {
            addCriterion("showsummary =", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryNotEqualTo(Byte value) {
            addCriterion("showsummary <>", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryGreaterThan(Byte value) {
            addCriterion("showsummary >", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryGreaterThanOrEqualTo(Byte value) {
            addCriterion("showsummary >=", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryLessThan(Byte value) {
            addCriterion("showsummary <", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryLessThanOrEqualTo(Byte value) {
            addCriterion("showsummary <=", value, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryIn(List<Byte> values) {
            addCriterion("showsummary in", values, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryNotIn(List<Byte> values) {
            addCriterion("showsummary not in", values, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryBetween(Byte value1, Byte value2) {
            addCriterion("showsummary between", value1, value2, "showsummary");
            return (Criteria) this;
        }

        public Criteria andShowsummaryNotBetween(Byte value1, Byte value2) {
            addCriterion("showsummary not between", value1, value2, "showsummary");
            return (Criteria) this;
        }

        public Criteria andDatelineIsNull() {
            addCriterion("dateline is null");
            return (Criteria) this;
        }

        public Criteria andDatelineIsNotNull() {
            addCriterion("dateline is not null");
            return (Criteria) this;
        }

        public Criteria andDatelineEqualTo(Integer value) {
            addCriterion("dateline =", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotEqualTo(Integer value) {
            addCriterion("dateline <>", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineGreaterThan(Integer value) {
            addCriterion("dateline >", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineGreaterThanOrEqualTo(Integer value) {
            addCriterion("dateline >=", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineLessThan(Integer value) {
            addCriterion("dateline <", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineLessThanOrEqualTo(Integer value) {
            addCriterion("dateline <=", value, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineIn(List<Integer> values) {
            addCriterion("dateline in", values, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotIn(List<Integer> values) {
            addCriterion("dateline not in", values, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineBetween(Integer value1, Integer value2) {
            addCriterion("dateline between", value1, value2, "dateline");
            return (Criteria) this;
        }

        public Criteria andDatelineNotBetween(Integer value1, Integer value2) {
            addCriterion("dateline not between", value1, value2, "dateline");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Integer value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Integer value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Integer value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Integer value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Integer> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Integer> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Integer value1, Integer value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_newsclass
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 12 14:32:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boka_newsclass
     *
     * @mbggenerated Wed Jul 12 14:32:37 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}