package com.boot.model.master;

public class BokaEduresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.id
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.oldid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer oldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.title
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.classid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.filesize
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.gradeclass
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String gradeclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.resourcetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Byte resourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.filetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.downurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String downurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.downclick
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String downclick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.otherurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String otherurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.moderate
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Byte moderate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.kid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.commend
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Byte commend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.uploader
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.priority
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.keyword
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.views
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.dateline
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.credit
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.rating
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Byte rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.targetid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer targetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.seotitle
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String seotitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.seodescription
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String seodescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.seokeywords
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String seokeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.linkid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Short linkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.mainbusid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer mainbusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.voteid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Short voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.dig
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Short dig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.eduresource6
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String eduresource6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.image
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.activetime
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer activetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.eduresource11
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String eduresource11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.eduresource13
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String eduresource13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.eduresource20
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private String eduresource20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boka_eduresource.downloads
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    private Integer downloads;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.id
     *
     * @return the value of boka_eduresource.id
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.id
     *
     * @param id the value for boka_eduresource.id
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.oldid
     *
     * @return the value of boka_eduresource.oldid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getOldid() {
        return oldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.oldid
     *
     * @param oldid the value for boka_eduresource.oldid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setOldid(Integer oldid) {
        this.oldid = oldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.title
     *
     * @return the value of boka_eduresource.title
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.title
     *
     * @param title the value for boka_eduresource.title
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.classid
     *
     * @return the value of boka_eduresource.classid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.classid
     *
     * @param classid the value for boka_eduresource.classid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setClassid(String classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.filesize
     *
     * @return the value of boka_eduresource.filesize
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.filesize
     *
     * @param filesize the value for boka_eduresource.filesize
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.gradeclass
     *
     * @return the value of boka_eduresource.gradeclass
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getGradeclass() {
        return gradeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.gradeclass
     *
     * @param gradeclass the value for boka_eduresource.gradeclass
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setGradeclass(String gradeclass) {
        this.gradeclass = gradeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.resourcetype
     *
     * @return the value of boka_eduresource.resourcetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Byte getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.resourcetype
     *
     * @param resourcetype the value for boka_eduresource.resourcetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setResourcetype(Byte resourcetype) {
        this.resourcetype = resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.filetype
     *
     * @return the value of boka_eduresource.filetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.filetype
     *
     * @param filetype the value for boka_eduresource.filetype
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.downurl
     *
     * @return the value of boka_eduresource.downurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getDownurl() {
        return downurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.downurl
     *
     * @param downurl the value for boka_eduresource.downurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDownurl(String downurl) {
        this.downurl = downurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.downclick
     *
     * @return the value of boka_eduresource.downclick
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getDownclick() {
        return downclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.downclick
     *
     * @param downclick the value for boka_eduresource.downclick
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDownclick(String downclick) {
        this.downclick = downclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.otherurl
     *
     * @return the value of boka_eduresource.otherurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getOtherurl() {
        return otherurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.otherurl
     *
     * @param otherurl the value for boka_eduresource.otherurl
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setOtherurl(String otherurl) {
        this.otherurl = otherurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.moderate
     *
     * @return the value of boka_eduresource.moderate
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Byte getModerate() {
        return moderate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.moderate
     *
     * @param moderate the value for boka_eduresource.moderate
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setModerate(Byte moderate) {
        this.moderate = moderate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.kid
     *
     * @return the value of boka_eduresource.kid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.kid
     *
     * @param kid the value for boka_eduresource.kid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setKid(String kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.commend
     *
     * @return the value of boka_eduresource.commend
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Byte getCommend() {
        return commend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.commend
     *
     * @param commend the value for boka_eduresource.commend
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setCommend(Byte commend) {
        this.commend = commend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.uploader
     *
     * @return the value of boka_eduresource.uploader
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.uploader
     *
     * @param uploader the value for boka_eduresource.uploader
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.priority
     *
     * @return the value of boka_eduresource.priority
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.priority
     *
     * @param priority the value for boka_eduresource.priority
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.keyword
     *
     * @return the value of boka_eduresource.keyword
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.keyword
     *
     * @param keyword the value for boka_eduresource.keyword
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.views
     *
     * @return the value of boka_eduresource.views
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.views
     *
     * @param views the value for boka_eduresource.views
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.dateline
     *
     * @return the value of boka_eduresource.dateline
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getDateline() {
        return dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.dateline
     *
     * @param dateline the value for boka_eduresource.dateline
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDateline(Integer dateline) {
        this.dateline = dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.credit
     *
     * @return the value of boka_eduresource.credit
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.credit
     *
     * @param credit the value for boka_eduresource.credit
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.rating
     *
     * @return the value of boka_eduresource.rating
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Byte getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.rating
     *
     * @param rating the value for boka_eduresource.rating
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setRating(Byte rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.targetid
     *
     * @return the value of boka_eduresource.targetid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.targetid
     *
     * @param targetid the value for boka_eduresource.targetid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setTargetid(Integer targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.seotitle
     *
     * @return the value of boka_eduresource.seotitle
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getSeotitle() {
        return seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.seotitle
     *
     * @param seotitle the value for boka_eduresource.seotitle
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setSeotitle(String seotitle) {
        this.seotitle = seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.seodescription
     *
     * @return the value of boka_eduresource.seodescription
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getSeodescription() {
        return seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.seodescription
     *
     * @param seodescription the value for boka_eduresource.seodescription
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setSeodescription(String seodescription) {
        this.seodescription = seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.seokeywords
     *
     * @return the value of boka_eduresource.seokeywords
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getSeokeywords() {
        return seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.seokeywords
     *
     * @param seokeywords the value for boka_eduresource.seokeywords
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setSeokeywords(String seokeywords) {
        this.seokeywords = seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.linkid
     *
     * @return the value of boka_eduresource.linkid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Short getLinkid() {
        return linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.linkid
     *
     * @param linkid the value for boka_eduresource.linkid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setLinkid(Short linkid) {
        this.linkid = linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.mainbusid
     *
     * @return the value of boka_eduresource.mainbusid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getMainbusid() {
        return mainbusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.mainbusid
     *
     * @param mainbusid the value for boka_eduresource.mainbusid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setMainbusid(Integer mainbusid) {
        this.mainbusid = mainbusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.voteid
     *
     * @return the value of boka_eduresource.voteid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Short getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.voteid
     *
     * @param voteid the value for boka_eduresource.voteid
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setVoteid(Short voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.dig
     *
     * @return the value of boka_eduresource.dig
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Short getDig() {
        return dig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.dig
     *
     * @param dig the value for boka_eduresource.dig
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDig(Short dig) {
        this.dig = dig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.eduresource6
     *
     * @return the value of boka_eduresource.eduresource6
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getEduresource6() {
        return eduresource6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.eduresource6
     *
     * @param eduresource6 the value for boka_eduresource.eduresource6
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setEduresource6(String eduresource6) {
        this.eduresource6 = eduresource6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.image
     *
     * @return the value of boka_eduresource.image
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.image
     *
     * @param image the value for boka_eduresource.image
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.activetime
     *
     * @return the value of boka_eduresource.activetime
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getActivetime() {
        return activetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.activetime
     *
     * @param activetime the value for boka_eduresource.activetime
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setActivetime(Integer activetime) {
        this.activetime = activetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.eduresource11
     *
     * @return the value of boka_eduresource.eduresource11
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getEduresource11() {
        return eduresource11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.eduresource11
     *
     * @param eduresource11 the value for boka_eduresource.eduresource11
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setEduresource11(String eduresource11) {
        this.eduresource11 = eduresource11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.eduresource13
     *
     * @return the value of boka_eduresource.eduresource13
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getEduresource13() {
        return eduresource13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.eduresource13
     *
     * @param eduresource13 the value for boka_eduresource.eduresource13
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setEduresource13(String eduresource13) {
        this.eduresource13 = eduresource13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.eduresource20
     *
     * @return the value of boka_eduresource.eduresource20
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public String getEduresource20() {
        return eduresource20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.eduresource20
     *
     * @param eduresource20 the value for boka_eduresource.eduresource20
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setEduresource20(String eduresource20) {
        this.eduresource20 = eduresource20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boka_eduresource.downloads
     *
     * @return the value of boka_eduresource.downloads
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public Integer getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boka_eduresource.downloads
     *
     * @param downloads the value for boka_eduresource.downloads
     *
     * @mbggenerated Fri Jul 07 17:12:17 CST 2017
     */
    public void setDownloads(Integer downloads) {
        this.downloads = downloads;
    }
}