package com.boot.model.master;

public class TempTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_table.id
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_table.title
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_table.dateline
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    private Integer dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_table.content
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_table.id
     *
     * @return the value of temp_table.id
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_table.id
     *
     * @param id the value for temp_table.id
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_table.title
     *
     * @return the value of temp_table.title
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_table.title
     *
     * @param title the value for temp_table.title
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_table.dateline
     *
     * @return the value of temp_table.dateline
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public Integer getDateline() {
        return dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_table.dateline
     *
     * @param dateline the value for temp_table.dateline
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public void setDateline(Integer dateline) {
        this.dateline = dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_table.content
     *
     * @return the value of temp_table.content
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_table.content
     *
     * @param content the value for temp_table.content
     *
     * @mbggenerated Thu Sep 14 19:03:53 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}