package com.boot.model.cluster;

public class JsCategoriesCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.id
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.parentId
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.name
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.deep
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String deep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.flag
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_copy.level4_code
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    private String level4Code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.id
     *
     * @return the value of js_categories_copy.id
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.id
     *
     * @param id the value for js_categories_copy.id
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.parentId
     *
     * @return the value of js_categories_copy.parentId
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.parentId
     *
     * @param parentid the value for js_categories_copy.parentId
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.name
     *
     * @return the value of js_categories_copy.name
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.name
     *
     * @param name the value for js_categories_copy.name
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.deep
     *
     * @return the value of js_categories_copy.deep
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.deep
     *
     * @param deep the value for js_categories_copy.deep
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setDeep(String deep) {
        this.deep = deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.flag
     *
     * @return the value of js_categories_copy.flag
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.flag
     *
     * @param flag the value for js_categories_copy.flag
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_copy.level4_code
     *
     * @return the value of js_categories_copy.level4_code
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public String getLevel4Code() {
        return level4Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_copy.level4_code
     *
     * @param level4Code the value for js_categories_copy.level4_code
     *
     * @mbggenerated Fri Jul 28 14:44:26 CST 2017
     */
    public void setLevel4Code(String level4Code) {
        this.level4Code = level4Code;
    }
}