package com.boot.model.cluster;

public class JsCategoriesDictCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_dict_copy.id
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_dict_copy.code
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_dict_copy.name
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_dict_copy.id
     *
     * @return the value of js_categories_dict_copy.id
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_dict_copy.id
     *
     * @param id the value for js_categories_dict_copy.id
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_dict_copy.code
     *
     * @return the value of js_categories_dict_copy.code
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_dict_copy.code
     *
     * @param code the value for js_categories_dict_copy.code
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_dict_copy.name
     *
     * @return the value of js_categories_dict_copy.name
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_dict_copy.name
     *
     * @param name the value for js_categories_dict_copy.name
     *
     * @mbggenerated Wed Aug 02 15:39:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}