package com.boot.model.cluster;

public class JsCategoriesRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.id
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.code
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level1
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level2
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level3
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level4
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level1Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level1sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level2Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level2sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level3Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level3sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_categories_relation.level4Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    private String level4sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.id
     *
     * @return the value of js_categories_relation.id
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.id
     *
     * @param id the value for js_categories_relation.id
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.code
     *
     * @return the value of js_categories_relation.code
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.code
     *
     * @param code the value for js_categories_relation.code
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level1
     *
     * @return the value of js_categories_relation.level1
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level1
     *
     * @param level1 the value for js_categories_relation.level1
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel1(String level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level2
     *
     * @return the value of js_categories_relation.level2
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level2
     *
     * @param level2 the value for js_categories_relation.level2
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel2(String level2) {
        this.level2 = level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level3
     *
     * @return the value of js_categories_relation.level3
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel3() {
        return level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level3
     *
     * @param level3 the value for js_categories_relation.level3
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel3(String level3) {
        this.level3 = level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level4
     *
     * @return the value of js_categories_relation.level4
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel4() {
        return level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level4
     *
     * @param level4 the value for js_categories_relation.level4
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel4(String level4) {
        this.level4 = level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level1Sort
     *
     * @return the value of js_categories_relation.level1Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel1sort() {
        return level1sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level1Sort
     *
     * @param level1sort the value for js_categories_relation.level1Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel1sort(String level1sort) {
        this.level1sort = level1sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level2Sort
     *
     * @return the value of js_categories_relation.level2Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel2sort() {
        return level2sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level2Sort
     *
     * @param level2sort the value for js_categories_relation.level2Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel2sort(String level2sort) {
        this.level2sort = level2sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level3Sort
     *
     * @return the value of js_categories_relation.level3Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel3sort() {
        return level3sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level3Sort
     *
     * @param level3sort the value for js_categories_relation.level3Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel3sort(String level3sort) {
        this.level3sort = level3sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_categories_relation.level4Sort
     *
     * @return the value of js_categories_relation.level4Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public String getLevel4sort() {
        return level4sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_categories_relation.level4Sort
     *
     * @param level4sort the value for js_categories_relation.level4Sort
     *
     * @mbggenerated Wed Jul 05 15:28:52 CST 2017
     */
    public void setLevel4sort(String level4sort) {
        this.level4sort = level4sort;
    }
}