package com.boot.model.cluster;

public class JsDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.id
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.code
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.value
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.desc
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.state
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.type
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.parentId
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_dict.resourceOrder
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    private Integer resourceorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.id
     *
     * @return the value of js_dict.id
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.id
     *
     * @param id the value for js_dict.id
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.code
     *
     * @return the value of js_dict.code
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.code
     *
     * @param code the value for js_dict.code
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.value
     *
     * @return the value of js_dict.value
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.value
     *
     * @param value the value for js_dict.value
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.desc
     *
     * @return the value of js_dict.desc
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.desc
     *
     * @param desc the value for js_dict.desc
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.state
     *
     * @return the value of js_dict.state
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.state
     *
     * @param state the value for js_dict.state
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.type
     *
     * @return the value of js_dict.type
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.type
     *
     * @param type the value for js_dict.type
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.parentId
     *
     * @return the value of js_dict.parentId
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.parentId
     *
     * @param parentid the value for js_dict.parentId
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_dict.resourceOrder
     *
     * @return the value of js_dict.resourceOrder
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public Integer getResourceorder() {
        return resourceorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_dict.resourceOrder
     *
     * @param resourceorder the value for js_dict.resourceOrder
     *
     * @mbggenerated Sun Jul 09 14:14:08 CST 2017
     */
    public void setResourceorder(Integer resourceorder) {
        this.resourceorder = resourceorder;
    }
}