package com.boot.model.cluster;

public class JsKnowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.id
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.phaseId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String phaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.subjectId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.name
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.parentId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.deep
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String deep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_knowledge.flag
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.id
     *
     * @return the value of js_knowledge.id
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.id
     *
     * @param id the value for js_knowledge.id
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.phaseId
     *
     * @return the value of js_knowledge.phaseId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getPhaseid() {
        return phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.phaseId
     *
     * @param phaseid the value for js_knowledge.phaseId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setPhaseid(String phaseid) {
        this.phaseid = phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.subjectId
     *
     * @return the value of js_knowledge.subjectId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.subjectId
     *
     * @param subjectid the value for js_knowledge.subjectId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.name
     *
     * @return the value of js_knowledge.name
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.name
     *
     * @param name the value for js_knowledge.name
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.parentId
     *
     * @return the value of js_knowledge.parentId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.parentId
     *
     * @param parentid the value for js_knowledge.parentId
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.deep
     *
     * @return the value of js_knowledge.deep
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.deep
     *
     * @param deep the value for js_knowledge.deep
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setDeep(String deep) {
        this.deep = deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_knowledge.flag
     *
     * @return the value of js_knowledge.flag
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_knowledge.flag
     *
     * @param flag the value for js_knowledge.flag
     *
     * @mbggenerated Mon Jul 03 10:05:32 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }
}