package com.boot.model.cluster;

public class JsResourceMidCategories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_mid_categories.id
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_mid_categories.busiId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    private String busiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_mid_categories.tCategoriesId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    private String tcategoriesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_mid_categories.categDeep
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    private String categdeep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_mid_categories.id
     *
     * @return the value of js_resource_mid_categories.id
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_mid_categories.id
     *
     * @param id the value for js_resource_mid_categories.id
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_mid_categories.busiId
     *
     * @return the value of js_resource_mid_categories.busiId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public String getBusiid() {
        return busiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_mid_categories.busiId
     *
     * @param busiid the value for js_resource_mid_categories.busiId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public void setBusiid(String busiid) {
        this.busiid = busiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_mid_categories.tCategoriesId
     *
     * @return the value of js_resource_mid_categories.tCategoriesId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public String getTcategoriesid() {
        return tcategoriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_mid_categories.tCategoriesId
     *
     * @param tcategoriesid the value for js_resource_mid_categories.tCategoriesId
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public void setTcategoriesid(String tcategoriesid) {
        this.tcategoriesid = tcategoriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_mid_categories.categDeep
     *
     * @return the value of js_resource_mid_categories.categDeep
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public String getCategdeep() {
        return categdeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_mid_categories.categDeep
     *
     * @param categdeep the value for js_resource_mid_categories.categDeep
     *
     * @mbggenerated Fri Jul 07 09:05:37 CST 2017
     */
    public void setCategdeep(String categdeep) {
        this.categdeep = categdeep;
    }
}