package com.boot.model.cluster;

public class JsResourceCopyWithBLOBs extends JsResourceCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_copy.content
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_copy.bookContent
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    private String bookcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource_copy.authorIntro
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    private String authorintro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_copy.content
     *
     * @return the value of js_resource_copy.content
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_copy.content
     *
     * @param content the value for js_resource_copy.content
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_copy.bookContent
     *
     * @return the value of js_resource_copy.bookContent
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public String getBookcontent() {
        return bookcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_copy.bookContent
     *
     * @param bookcontent the value for js_resource_copy.bookContent
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public void setBookcontent(String bookcontent) {
        this.bookcontent = bookcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource_copy.authorIntro
     *
     * @return the value of js_resource_copy.authorIntro
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public String getAuthorintro() {
        return authorintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource_copy.authorIntro
     *
     * @param authorintro the value for js_resource_copy.authorIntro
     *
     * @mbggenerated Fri Jul 28 15:45:54 CST 2017
     */
    public void setAuthorintro(String authorintro) {
        this.authorintro = authorintro;
    }
}