package com.boot.model.cluster;

import java.util.Date;

public class JsResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.id
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.contributeId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String contributeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.title
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.fileName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.fileSize
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.filePath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.pdfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String pdfpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.swfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String swfpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.conertState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String conertstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.conertDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Date conertdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceTypeOneLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcetypeonelevelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceTypeOneLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcetypeonelevelvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceTypeTwoLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcetypetwolevelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceTypeTwoLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcetypetwolevelvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceFormatId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourceformatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceFormatValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourceformatvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.categoriesCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String categoriescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.knowledgeCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String knowledgecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.wordCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer wordcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.timeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer timecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.mapCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer mapcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.author
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.workplace
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.userId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.userName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.storageId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String storageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.storageName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String storagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.createDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.downclick
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String downclick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.likeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String likecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.views
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.collectionCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String collectioncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.resourceType
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String resourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.copyright
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String copyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.yearMonth
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String yearmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.state
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.lastState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String laststate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.approverId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String approverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.approver
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String approver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.version
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.phaseId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String phaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.phase
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.subjectId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.subject
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.isFree
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String isfree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.cost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.totalCost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer totalcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.coverPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String coverpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.origin
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.hotResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String hotresource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.recomResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String recomresource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.isUpdate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String isupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.flag
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.id
     *
     * @return the value of js_resource.id
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.id
     *
     * @param id the value for js_resource.id
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.contributeId
     *
     * @return the value of js_resource.contributeId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getContributeid() {
        return contributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.contributeId
     *
     * @param contributeid the value for js_resource.contributeId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setContributeid(String contributeid) {
        this.contributeid = contributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.title
     *
     * @return the value of js_resource.title
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.title
     *
     * @param title the value for js_resource.title
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.fileName
     *
     * @return the value of js_resource.fileName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.fileName
     *
     * @param filename the value for js_resource.fileName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceCode
     *
     * @return the value of js_resource.resourceCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcecode() {
        return resourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceCode
     *
     * @param resourcecode the value for js_resource.resourceCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcecode(String resourcecode) {
        this.resourcecode = resourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.fileSize
     *
     * @return the value of js_resource.fileSize
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.fileSize
     *
     * @param filesize the value for js_resource.fileSize
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.filePath
     *
     * @return the value of js_resource.filePath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.filePath
     *
     * @param filepath the value for js_resource.filePath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.pdfPath
     *
     * @return the value of js_resource.pdfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getPdfpath() {
        return pdfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.pdfPath
     *
     * @param pdfpath the value for js_resource.pdfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setPdfpath(String pdfpath) {
        this.pdfpath = pdfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.swfPath
     *
     * @return the value of js_resource.swfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getSwfpath() {
        return swfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.swfPath
     *
     * @param swfpath the value for js_resource.swfPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setSwfpath(String swfpath) {
        this.swfpath = swfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.conertState
     *
     * @return the value of js_resource.conertState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getConertstate() {
        return conertstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.conertState
     *
     * @param conertstate the value for js_resource.conertState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setConertstate(String conertstate) {
        this.conertstate = conertstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.conertDate
     *
     * @return the value of js_resource.conertDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Date getConertdate() {
        return conertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.conertDate
     *
     * @param conertdate the value for js_resource.conertDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setConertdate(Date conertdate) {
        this.conertdate = conertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceTypeOneLevelId
     *
     * @return the value of js_resource.resourceTypeOneLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcetypeonelevelid() {
        return resourcetypeonelevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceTypeOneLevelId
     *
     * @param resourcetypeonelevelid the value for js_resource.resourceTypeOneLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcetypeonelevelid(String resourcetypeonelevelid) {
        this.resourcetypeonelevelid = resourcetypeonelevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceTypeOneLevelValue
     *
     * @return the value of js_resource.resourceTypeOneLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcetypeonelevelvalue() {
        return resourcetypeonelevelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceTypeOneLevelValue
     *
     * @param resourcetypeonelevelvalue the value for js_resource.resourceTypeOneLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcetypeonelevelvalue(String resourcetypeonelevelvalue) {
        this.resourcetypeonelevelvalue = resourcetypeonelevelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceTypeTwoLevelId
     *
     * @return the value of js_resource.resourceTypeTwoLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcetypetwolevelid() {
        return resourcetypetwolevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceTypeTwoLevelId
     *
     * @param resourcetypetwolevelid the value for js_resource.resourceTypeTwoLevelId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcetypetwolevelid(String resourcetypetwolevelid) {
        this.resourcetypetwolevelid = resourcetypetwolevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceTypeTwoLevelValue
     *
     * @return the value of js_resource.resourceTypeTwoLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcetypetwolevelvalue() {
        return resourcetypetwolevelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceTypeTwoLevelValue
     *
     * @param resourcetypetwolevelvalue the value for js_resource.resourceTypeTwoLevelValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcetypetwolevelvalue(String resourcetypetwolevelvalue) {
        this.resourcetypetwolevelvalue = resourcetypetwolevelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceFormatId
     *
     * @return the value of js_resource.resourceFormatId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourceformatid() {
        return resourceformatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceFormatId
     *
     * @param resourceformatid the value for js_resource.resourceFormatId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourceformatid(String resourceformatid) {
        this.resourceformatid = resourceformatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceFormatValue
     *
     * @return the value of js_resource.resourceFormatValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourceformatvalue() {
        return resourceformatvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceFormatValue
     *
     * @param resourceformatvalue the value for js_resource.resourceFormatValue
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourceformatvalue(String resourceformatvalue) {
        this.resourceformatvalue = resourceformatvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.categoriesCode
     *
     * @return the value of js_resource.categoriesCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getCategoriescode() {
        return categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.categoriesCode
     *
     * @param categoriescode the value for js_resource.categoriesCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCategoriescode(String categoriescode) {
        this.categoriescode = categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.knowledgeCode
     *
     * @return the value of js_resource.knowledgeCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getKnowledgecode() {
        return knowledgecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.knowledgeCode
     *
     * @param knowledgecode the value for js_resource.knowledgeCode
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setKnowledgecode(String knowledgecode) {
        this.knowledgecode = knowledgecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.wordCount
     *
     * @return the value of js_resource.wordCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getWordcount() {
        return wordcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.wordCount
     *
     * @param wordcount the value for js_resource.wordCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setWordcount(Integer wordcount) {
        this.wordcount = wordcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.timeCount
     *
     * @return the value of js_resource.timeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getTimecount() {
        return timecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.timeCount
     *
     * @param timecount the value for js_resource.timeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setTimecount(Integer timecount) {
        this.timecount = timecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.mapCount
     *
     * @return the value of js_resource.mapCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getMapcount() {
        return mapcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.mapCount
     *
     * @param mapcount the value for js_resource.mapCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setMapcount(Integer mapcount) {
        this.mapcount = mapcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.author
     *
     * @return the value of js_resource.author
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.author
     *
     * @param author the value for js_resource.author
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.workplace
     *
     * @return the value of js_resource.workplace
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.workplace
     *
     * @param workplace the value for js_resource.workplace
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.userId
     *
     * @return the value of js_resource.userId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.userId
     *
     * @param userid the value for js_resource.userId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.userName
     *
     * @return the value of js_resource.userName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.userName
     *
     * @param username the value for js_resource.userName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.storageId
     *
     * @return the value of js_resource.storageId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.storageId
     *
     * @param storageid the value for js_resource.storageId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setStorageid(String storageid) {
        this.storageid = storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.storageName
     *
     * @return the value of js_resource.storageName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getStoragename() {
        return storagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.storageName
     *
     * @param storagename the value for js_resource.storageName
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setStoragename(String storagename) {
        this.storagename = storagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.createDate
     *
     * @return the value of js_resource.createDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.createDate
     *
     * @param createdate the value for js_resource.createDate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.downclick
     *
     * @return the value of js_resource.downclick
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getDownclick() {
        return downclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.downclick
     *
     * @param downclick the value for js_resource.downclick
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setDownclick(String downclick) {
        this.downclick = downclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.likeCount
     *
     * @return the value of js_resource.likeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.likeCount
     *
     * @param likecount the value for js_resource.likeCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setLikecount(String likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.views
     *
     * @return the value of js_resource.views
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.views
     *
     * @param views the value for js_resource.views
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setViews(String views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.collectionCount
     *
     * @return the value of js_resource.collectionCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getCollectioncount() {
        return collectioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.collectionCount
     *
     * @param collectioncount the value for js_resource.collectionCount
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCollectioncount(String collectioncount) {
        this.collectioncount = collectioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.resourceType
     *
     * @return the value of js_resource.resourceType
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.resourceType
     *
     * @param resourcetype the value for js_resource.resourceType
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setResourcetype(String resourcetype) {
        this.resourcetype = resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.copyright
     *
     * @return the value of js_resource.copyright
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.copyright
     *
     * @param copyright the value for js_resource.copyright
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.yearMonth
     *
     * @return the value of js_resource.yearMonth
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getYearmonth() {
        return yearmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.yearMonth
     *
     * @param yearmonth the value for js_resource.yearMonth
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setYearmonth(String yearmonth) {
        this.yearmonth = yearmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.state
     *
     * @return the value of js_resource.state
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.state
     *
     * @param state the value for js_resource.state
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.lastState
     *
     * @return the value of js_resource.lastState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getLaststate() {
        return laststate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.lastState
     *
     * @param laststate the value for js_resource.lastState
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setLaststate(String laststate) {
        this.laststate = laststate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.approverId
     *
     * @return the value of js_resource.approverId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getApproverid() {
        return approverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.approverId
     *
     * @param approverid the value for js_resource.approverId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setApproverid(String approverid) {
        this.approverid = approverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.approver
     *
     * @return the value of js_resource.approver
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getApprover() {
        return approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.approver
     *
     * @param approver the value for js_resource.approver
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setApprover(String approver) {
        this.approver = approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.version
     *
     * @return the value of js_resource.version
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.version
     *
     * @param version the value for js_resource.version
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.phaseId
     *
     * @return the value of js_resource.phaseId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getPhaseid() {
        return phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.phaseId
     *
     * @param phaseid the value for js_resource.phaseId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setPhaseid(String phaseid) {
        this.phaseid = phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.phase
     *
     * @return the value of js_resource.phase
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.phase
     *
     * @param phase the value for js_resource.phase
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.subjectId
     *
     * @return the value of js_resource.subjectId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.subjectId
     *
     * @param subjectid the value for js_resource.subjectId
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.subject
     *
     * @return the value of js_resource.subject
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.subject
     *
     * @param subject the value for js_resource.subject
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.isFree
     *
     * @return the value of js_resource.isFree
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getIsfree() {
        return isfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.isFree
     *
     * @param isfree the value for js_resource.isFree
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setIsfree(String isfree) {
        this.isfree = isfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.cost
     *
     * @return the value of js_resource.cost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.cost
     *
     * @param cost the value for js_resource.cost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.totalCost
     *
     * @return the value of js_resource.totalCost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getTotalcost() {
        return totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.totalCost
     *
     * @param totalcost the value for js_resource.totalCost
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setTotalcost(Integer totalcost) {
        this.totalcost = totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.coverPath
     *
     * @return the value of js_resource.coverPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getCoverpath() {
        return coverpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.coverPath
     *
     * @param coverpath the value for js_resource.coverPath
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setCoverpath(String coverpath) {
        this.coverpath = coverpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.origin
     *
     * @return the value of js_resource.origin
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.origin
     *
     * @param origin the value for js_resource.origin
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.hotResource
     *
     * @return the value of js_resource.hotResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getHotresource() {
        return hotresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.hotResource
     *
     * @param hotresource the value for js_resource.hotResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setHotresource(String hotresource) {
        this.hotresource = hotresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.recomResource
     *
     * @return the value of js_resource.recomResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getRecomresource() {
        return recomresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.recomResource
     *
     * @param recomresource the value for js_resource.recomResource
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setRecomresource(String recomresource) {
        this.recomresource = recomresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.isUpdate
     *
     * @return the value of js_resource.isUpdate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getIsupdate() {
        return isupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.isUpdate
     *
     * @param isupdate the value for js_resource.isUpdate
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setIsupdate(String isupdate) {
        this.isupdate = isupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.flag
     *
     * @return the value of js_resource.flag
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.flag
     *
     * @param flag the value for js_resource.flag
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}