package com.boot.model.cluster;

public class JsResourceWithBLOBs extends JsResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.content
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.bookContent
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String bookcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_resource.authorIntro
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    private String authorintro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.content
     *
     * @return the value of js_resource.content
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.content
     *
     * @param content the value for js_resource.content
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.bookContent
     *
     * @return the value of js_resource.bookContent
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getBookcontent() {
        return bookcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.bookContent
     *
     * @param bookcontent the value for js_resource.bookContent
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setBookcontent(String bookcontent) {
        this.bookcontent = bookcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_resource.authorIntro
     *
     * @return the value of js_resource.authorIntro
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public String getAuthorintro() {
        return authorintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_resource.authorIntro
     *
     * @param authorintro the value for js_resource.authorIntro
     *
     * @mbggenerated Thu Sep 14 18:47:55 CST 2017
     */
    public void setAuthorintro(String authorintro) {
        this.authorintro = authorintro;
    }
}