package com.boot.model.cluster;

import java.util.ArrayList;
import java.util.List;

public class TempEbookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public TempEbookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoriescodeIsNull() {
            addCriterion("categoriesCode is null");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeIsNotNull() {
            addCriterion("categoriesCode is not null");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeEqualTo(String value) {
            addCriterion("categoriesCode =", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeNotEqualTo(String value) {
            addCriterion("categoriesCode <>", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeGreaterThan(String value) {
            addCriterion("categoriesCode >", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeGreaterThanOrEqualTo(String value) {
            addCriterion("categoriesCode >=", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeLessThan(String value) {
            addCriterion("categoriesCode <", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeLessThanOrEqualTo(String value) {
            addCriterion("categoriesCode <=", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeLike(String value) {
            addCriterion("categoriesCode like", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeNotLike(String value) {
            addCriterion("categoriesCode not like", value, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeIn(List<String> values) {
            addCriterion("categoriesCode in", values, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeNotIn(List<String> values) {
            addCriterion("categoriesCode not in", values, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeBetween(String value1, String value2) {
            addCriterion("categoriesCode between", value1, value2, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCategoriescodeNotBetween(String value1, String value2) {
            addCriterion("categoriesCode not between", value1, value2, "categoriescode");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Long value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Long value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Long value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Long value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Long value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Long value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Long> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Long> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Long value1, Long value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Long value1, Long value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNull() {
            addCriterion("rtype is null");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNotNull() {
            addCriterion("rtype is not null");
            return (Criteria) this;
        }

        public Criteria andRtypeEqualTo(int value) {
            addCriterion("rtype =", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotEqualTo(Byte value) {
            addCriterion("rtype <>", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThan(Byte value) {
            addCriterion("rtype >", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("rtype >=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThan(Byte value) {
            addCriterion("rtype <", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThanOrEqualTo(Byte value) {
            addCriterion("rtype <=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeIn(List<Byte> values) {
            addCriterion("rtype in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotIn(List<Byte> values) {
            addCriterion("rtype not in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeBetween(Byte value1, Byte value2) {
            addCriterion("rtype between", value1, value2, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotBetween(Byte value1, Byte value2) {
            addCriterion("rtype not between", value1, value2, "rtype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table temp_ebook
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 02 14:58:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table temp_ebook
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}