package com.boot.model.cluster;

public class Temp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.categoriesCode
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    private String categoriescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.count
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    private Long count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.categoriesCode
     *
     * @return the value of temp.categoriesCode
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    public String getCategoriescode() {
        return categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.categoriesCode
     *
     * @param categoriescode the value for temp.categoriesCode
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    public void setCategoriescode(String categoriescode) {
        this.categoriescode = categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.count
     *
     * @return the value of temp.count
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.count
     *
     * @param count the value for temp.count
     *
     * @mbggenerated Mon Jul 17 09:36:11 CST 2017
     */
    public void setCount(Long count) {
        this.count = count;
    }
}