package com.boot.model.cluster;

public class TempTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_teacher.categoriesCode
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    private String categoriescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_teacher.count
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    private Long count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_teacher.rtype
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    private Byte rtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_teacher.categoriesCode
     *
     * @return the value of temp_teacher.categoriesCode
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public String getCategoriescode() {
        return categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_teacher.categoriesCode
     *
     * @param categoriescode the value for temp_teacher.categoriesCode
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void setCategoriescode(String categoriescode) {
        this.categoriescode = categoriescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_teacher.count
     *
     * @return the value of temp_teacher.count
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_teacher.count
     *
     * @param count the value for temp_teacher.count
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_teacher.rtype
     *
     * @return the value of temp_teacher.rtype
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public Byte getRtype() {
        return rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_teacher.rtype
     *
     * @param rtype the value for temp_teacher.rtype
     *
     * @mbggenerated Wed Aug 02 14:58:49 CST 2017
     */
    public void setRtype(Byte rtype) {
        this.rtype = rtype;
    }
}